// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaEi4ldYVJd8ggFjaZY60qNzZyVT8wgcY',
    appId: '1:979426013726:web:321055659d28be3588740f',
    messagingSenderId: '979426013726',
    projectId: 'todo-app-aa5ef',
    authDomain: 'todo-app-aa5ef.firebaseapp.com',
    databaseURL:
        'https://todo-app-aa5ef-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'todo-app-aa5ef.firebasestorage.app',
    measurementId: 'G-16GR9C56YQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyR2OMRzK1FQRF5EMp1sQFOL-2gmvGHXo',
    appId: '1:979426013726:android:68436388e83f79a888740f',
    messagingSenderId: '979426013726',
    projectId: 'todo-app-aa5ef',
    databaseURL:
        'https://todo-app-aa5ef-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'todo-app-aa5ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1HO6i57lWUpCCBSgvD9FGuA5hB686NVM',
    appId: '1:979426013726:ios:ee3bf9aba7c73d9188740f',
    messagingSenderId: '979426013726',
    projectId: 'todo-app-aa5ef',
    databaseURL:
        'https://todo-app-aa5ef-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'todo-app-aa5ef.firebasestorage.app',
    iosBundleId: 'com.example.maTodoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1HO6i57lWUpCCBSgvD9FGuA5hB686NVM',
    appId: '1:979426013726:ios:ee3bf9aba7c73d9188740f',
    messagingSenderId: '979426013726',
    projectId: 'todo-app-aa5ef',
    databaseURL:
        'https://todo-app-aa5ef-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'todo-app-aa5ef.firebasestorage.app',
    iosBundleId: 'com.example.maTodoFlutter',
  );
}
